[package]
name = "mqtt_to_system_command"
version = "0.9.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rumqttc = "0.25.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.48.0", features = ["full"] }
