name: Release Crate
on:
  release:
    types:
      - published
jobs:
  build:
    name: Crate release
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2
      - name: Downloading rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publishing crate
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
